# Dev container
services:
  dev:
    image: node:22.12.0-alpine3.20

    # env_file:
    #   - .env
    # ports:
    #   - "${PORT:-8080}:${PORT:-8080}"

    working_dir: /app
    volumes:
      - ./:/app

    command: npm run dev
    stop_signal: SIGKILL
